version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: solar-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"   # Management UI: http://localhost:15672 (guest/guest)
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 6

  redis:
    image: redis:7-alpine
    container_name: solar-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  ingestor:
    build: ./src/ingestor
    container_name: solar-ingestor
    environment:
      - NASA_API_KEY=DEMO_KEY
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
