worker_processes 1;

events {
    worker_connections 1024;
}

http {
    # rate limiting: 10 req/s por IP, zona de 10MB
    limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;
    limit_req_status 429;

    upstream ingestor {
        server ingestor:3001;
    }

    upstream alert_svc {
        server alert-service:3002;
    }

    server {
        listen 80;

        # rota para o Ingestor Service
        location /api/ingest/ {
            limit_req zone=api burst=5 nodelay;
            rewrite ^/api/ingest/(.*)$ /ingest/$1 break;
            proxy_pass http://ingestor;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # rota para o Alert Service
        location /api/alerts {
            limit_req zone=api burst=5 nodelay;
            proxy_pass http://alert_svc/alerts;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # healthcheck do gateway
        location /health {
            return 200 '{"status":"ok","gateway":"nginx"}';
            add_header Content-Type application/json;
        }
    }
}
